// @ts-ignore generated by pnpm build:worker; absent before the first build
import nextWorker from "./.open-next/worker.js";
import { cleanup } from "./src/server/auth";

export default {
  fetch: nextWorker.fetch,
  scheduled(_event: ScheduledController, env: Env) {
    return cleanup(env);
  },
} satisfies ExportedHandler<Env>;
